version: '3.8'

services:
  # Python application container untuk scraping berita
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: berita-scraper
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      # Volume untuk cache data
      - ./cache:/app/cache
    depends_on:
      - chrome
    networks:
      - scraper-network
    restart: unless-stopped

  # Standalone Chrome container untuk Selenium
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome-berita
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - scraper-network
    restart: unless-stopped

# Network untuk komunikasi antar container
networks:
  scraper-network:
    driver: bridge 